name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        include:
          - output_target: linux-x86_64
            os: ubuntu-22.04
            target: x86_64-unknown-linux-musl

          - output_target: linux-aarch64
            os: ubuntu-22.04
            target: aarch64-unknown-linux-musl
            container: ghcr.io/cross-rs/aarch64-unknown-linux-musl:edge

          - output_target: win-x86_64
            os: windows-2022
            target: x86_64-pc-windows-msvc
            output_postfix: '.exe'

          - output_target: darwin-x86_64
            os: macOS-12
            target: x86_64-apple-darwin

          - output_target: darwin-aarch64
            os: macOS-12
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run build script
        env:
          TARGET: ${{ matrix.target }}
          OUTPUT_TARGET: ${{ matrix.output_target }}
        run: ./build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ruvchain-connector-${{ matrix.output_target }}
          path: output/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: "output/*"
